---
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart icecast2
  ansible.builtin.systemd:
    name: icecast2
    state: restarted

- name: Restart liquidsoap
  ansible.builtin.systemd:
    name: liquidsoap-rhythm-place
    state: restarted
