---
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart rhythm icecast2
  ansible.builtin.systemd:
    name: rhythm-icecast2
    state: restarted
    daemon_reload: true

- name: Restart rhythm liquidsoap
  ansible.builtin.systemd:
    name: rhythm-liquidsoap
    state: restarted
    daemon_reload: true
