/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSongChar123GenreChar125RouteImport } from './routes/api/song/{-$genre}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSongChar123GenreChar125Route =
  ApiSongChar123GenreChar125RouteImport.update({
    id: '/api/song/{-$genre}',
    path: '/api/song/{-$genre}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/song/{-$genre}': typeof ApiSongChar123GenreChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/song/{-$genre}': typeof ApiSongChar123GenreChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/song/{-$genre}': typeof ApiSongChar123GenreChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/song/{-$genre}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/song/{-$genre}'
  id: '__root__' | '/' | '/api/song/{-$genre}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSongChar123GenreChar125Route: typeof ApiSongChar123GenreChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/song/{-$genre}': {
      id: '/api/song/{-$genre}'
      path: '/api/song/{-$genre}'
      fullPath: '/api/song/{-$genre}'
      preLoaderRoute: typeof ApiSongChar123GenreChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSongChar123GenreChar125Route: ApiSongChar123GenreChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
